const Components = options => [
  {
    key: 'Text',
    name: 'Text',
    editorType: 'wPlainText',
    displayType: 'wPlainText',
    text: '',
    property: 'text',
    alignment: { label: 'Left', value: 'left' },
  },
  {
    key: 'RichText',
    name: 'Rich Text',
    editorType: 'wRichText',
    displayType: 'wRichText',
    text: '',
    property: 'text',
  },
  {
    key: 'Link',
    name: 'Link',
    editorType: 'wLink',
    displayType: 'wLink',
    type: 'page',
    showOnDesktop: true,
    showOnTablet: true,
    showOnMobile: true,
  },
  {
    key: 'Menu',
    name: 'Menu',
    editorType: 'Menu',
    displayType: 'Menu',
    type: 'page', // what is this?
    links: [],
    showOnDesktop: true,
    showOnTablet: true,
    showOnMobile: true,
  },
  {
    key: 'Carousel',
    name: 'Carousel',
    editorType: 'wList',
    displayType: 'wCarousel',
    reversed: false,
    title: '',
    description: '',
    button: {
      type: 'page',
      text: '',
      href: '',
    },
    property: 'items',
    items: [
      {
        text: {
          title: '',
          description: '',
        },
        button: {
          text: '',
          icon: undefined,
          href: '',
          type: 'page',
        },
        image: {
          imageId: undefined,
          crop: {},
        },
      },
    ],
  },
  {
    key: 'Listings',
    name: 'Listings',
    editorType: 'wListings',
    displayType: 'wListings',
    property: 'categoryFilter',
    categoryFilter: {},
  },
  {
    key: 'SplitContent',
    name: 'Split Content',
    editorType: 'wSplitContent',
    displayType: 'wSplitContent',
    property: 'width',
    contents: { left: [], right: [] },
    width: '6',
  },
  {
    key: 'Anchor',
    name: 'Anchor',
    editorType: 'AnchorMenu',
    displayType: 'Anchor',
    id: '',
    marginTop: 0,
  },
  {
    key: 'ContactIcon',
    name: 'Contact Icon',
    editorType: 'ContactIcon',
    displayType: 'ContactIcon',
  },
  ...options.components,
];

export { Components };
