const Components = options => [
  {
    key: 'Text',
    name: 'Text',
    editorType: 'wPlainText',
    displayType: 'wPlainText',
    text: '',
    property: 'text',
    alignment: { label: 'Left', value: 'left' },
  },
  {
    key: 'RichText',
    name: 'Rich Text',
    editorType: 'wRichText',
    displayType: 'wRichText',
    text: '',
    property: 'text',
  },
  {
    key: 'Link',
    name: 'Link',
    editorType: 'wLink',
    displayType: 'wLink',
    type: 'page',
    showOnDesktop: true,
    showOnTablet: true,
    showOnMobile: true,
  },
  {
    key: 'LinkGroup',
    name: 'Link Group',
    editorType: 'wLinkGroup',
    displayType: 'wLinkGroup',
    type: 'page',
    links: [],
    showOnDesktop: true,
    showOnTablet: true,
    showOnMobile: true,
  },
  {
    key: 'Carousel',
    name: 'Carousel',
    editorType: 'wCarousel',
    displayType: 'wCarousel',
    reversed: false,
    title: '',
    description: '',
    button: {
      type: 'page',
      text: '',
      href: '',
    },
    property: 'items',
    items: [
      {
        text: {
          title: '',
          description: '',
        },
        button: {
          type: 'page',
          text: '',
          icon: undefined,
          href: '',
        },
        image: {
          imageId: '',
          crop: {},
        },
      },
    ],
  },
  {
    key: 'Listings',
    name: 'Listings',
    editorType: 'wListings',
    displayType: 'wListings',
    property: 'categoryFilter',
    categoryFilter: {},
  },
  {
    key: 'EditImage',
    name: 'Edit Image',
    editorType: 'wEditImage',
    displayType: 'wEditImage',
    property: 'data',
    data: {
      imageId: '',
      // crop: {},
    },
  },
  ...options.components,
];

export { Components };
