const Components = options => [
  { key: 'Text', name: 'Text', editorType: 'wPlainText', displayType: 'wPlainText', text: 'test' },
  {
    key: 'RichText',
    name: 'Rich Text',
    editorType: 'wRichText',
    displayType: 'wRichText',
    text: '',
    property: 'text',
  },
  {
    key: 'LinkGroup',
    name: 'Link Group',
    editorType: 'wLinkGroup',
    displayType: 'wLinkGroup',
    type: 'page',
    links: [],
    showOnDesktop: true,
    showOnTablet: true,
    showOnMobile: true,
  },
  {
    key: 'Carousel',
    name: 'Carousel',
    editorType: 'wCarousel',
    displayType: 'wCarousel',
    reversed: false,
    title: '',
    description: '',
    items: [
      {
        title: '',
        description: '',
        ctaText: '',
        ctaIcon: undefined,
        ctaLink: undefined,
        image: undefined,
      },
    ],
  },
  {
    key: 'Listings',
    name: 'Listings',
    editorType: 'wListings',
    displayType: 'wListings',
    categories: [],
  },
  {
    key: 'Container',
    name: 'Container',
    editorType: 'wContainer',
    displayType: 'wContainer',
    contents: [],
  },
  {
    key: 'Image',
    value: 'Test Image',
    editorType: 'wImage',
    displayType: 'wImage',
    data: undefined,
  },
  ...options.components,
];

export { Components };
